name: Build site daily or on master update

on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: joelwmale/webhook-action@master
        with:
          # set this to Netlify build webhook URL
          # https://docs.netlify.com/configure-builds/build-hooks/
          url: ${{ secrets.NETLIFY_BUILD_WEBHOOK_URL }}
